#!/bin/sh
set -e # on non-zero return code from command, exit program
dir="$(git rev-parse --show-toplevel)" # Print repo root
trap 'rm -f "$dir/.$$.tags"' EXIT # delete .pid.tags on program exit
ctags -R --tag-relative --extra=+f -f "$dir/.$$.tags"
mv "$dir/.$$.tags" "$dir/.tags" # if nothing fails, move the generated tag to git root/.tags

